# version is now using "compose spec"
# v2 and v3 are now combined!
# docker-compose v1.27+ required
version: "2.2"
services:


  alfresco:
    image: alfresco/alfresco-content-repository-community:7.1.0
    mem_limit: 10g
    environment:
        JAVA_TOOL_OPTIONS: "
                -Dencryption.keystore.type=JCEKS
                -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
                -Dencryption.keyAlgorithm=DESede
                -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
                -Dmetadata-keystore.password=mp6yc0UD9e
                -Dmetadata-keystore.aliases=metadata
                -Dmetadata-keystore.metadata.password=oKIWzVdEdA
                -Dmetadata-keystore.metadata.algorithm=DESede
                "
        JAVA_OPTS: "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=postgres
                -Ddb.password=P@ssw0rd
                -Ddb.url=jdbc:postgresql://host.docker.internal:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.http.connection.timeout=1000
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
                -Dcsrf.filter.enabled=false
                -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80
                "
    volumes:
      - alfresco_data:/usr/local/tomcat/alf_data
  transform-core-aio:
     image: alfresco/alfresco-transform-core-aio:2.5.3
     mem_limit: 1536m
     environment:
        JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
     ports:
         - 8090:8090

  share:
     image: alfresco/alfresco-share:7.1.0.1
     mem_limit: 2560m
     environment:
         REPO_HOST: "alfresco"
         REPO_PORT: "8080"
         JAVA_OPTS: "
             -XX:MinRAMPercentage=50
             -XX:MaxRAMPercentage=80
             -Dalfresco.host=localhost
             -Dalfresco.port=8080
             -Dalfresco.context=alfresco
             -Dalfresco.protocol=http
             "

  solr6:
     image: alfresco/alfresco-search-services:2.0.2
     mem_limit: 5g
     environment:
         #Solr needs to know how to register itself with Alfresco
         - SOLR_ALFRESCO_HOST=alfresco
         - SOLR_ALFRESCO_PORT=8080
         #Alfresco needs to know how to call solr
         - SOLR_SOLR_HOST=solr6
         - SOLR_SOLR_PORT=8983
         #Create the default alfresco and archive cores
         - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
         #HTTP by default
         - ALFRESCO_SECURE_COMMS=none
     ports:
         - 8083:8983 #Browser port

  activemq:
     image: alfresco/alfresco-activemq:5.16.1
     mem_limit: 1g
     ports:
         - 8161:8161 # Web Console
         - 5673:5672 # AMQP
         - 61616:61616 # OpenWire
         - 61613:61613 # STOMP
  proxy:
     image: alfresco/alfresco-acs-nginx:3.1.1
     mem_limit: 128m
     environment:
         DISABLE_PROMETHEUS: "true"
         DISABLE_SYNCSERVICE: "true"
         DISABLE_ADW: "true"
         USE_SSL: "true"
     depends_on:
         - alfresco
     ports:
         - 8080:8080
         - 8081:443
     restart: always
     links:
         - alfresco
         - share
     volumes:
       - ./identity-server-volumes/:/etc/nginx/ssl/ 
volumes:
  alfresco_data:
